name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [24]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run tests
      run: rebar3 do eunit, ct
    - name: Run Cover
      run: rebar3 cover
